server:
  port: 9090


spring:
  h2:
    console.enabled: true
  #  datasource:
  #    url: jdbc:h2:file:~/data/ButuDB
  #    username: sa
  #    password: password
  #    driverClassName: org.h2.Driver
  jpa:
    #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  application:
    name: GOODS_DETAILS

  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/butudb
    username: root
    password: Butuna@16847

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

